import { allPosts} from "contentlayer/generated"
import PostsList from "../components/PostsList";
import PostPagination from "../components/PostPagination";
import { getPagination } from "@/utils/pagination";


export const metadata = {
  title: "Lista de todos los post",
  description: "Description posts - Generated by create next app",
};

const Posts = () => {
  
  const {currentPosts, totalPages} = getPagination(allPosts);

  return (
    <div>
      <div className="grid gap-4">
        <PostsList posts={currentPosts} />
        {totalPages > 1 && (
          <PostPagination totalPages={totalPages} />
        )}
        
      </div>
    </div>
  )
}

export default Posts
